#!/bin/bash

CONDITION="<TODO>"

DATA_DIRECTORY="<TODO>"
CELESTA_DIRECTORY="<TODO>"
SCRIPT_DIRECTORY="<TODO>"

COLORMAP="<TODO>"

SIGNATURE_MATRIX="$CELESTA_DIRECTORY/signature_matrices/$CONDITION/<TODO>.csv"

IMAGE_DIRECTORY="$DATA_DIRECTORY/$CONDITION"
ASSIGNMENTS_DIRECTORY="$IMAGE_DIRECTORY/assignments"

TOPOLOGY_SCRIPT="$SCRIPT_DIRECTORY/persistent_homology.py"

python3 "$TOPOLOGY_SCRIPT" \
    --data_directory "$ASSIGNMENTS_DIRECTORY" \
    --save_path "$IMAGE_DIRECTORY"
