[project]
name = "epochs"
version = "0.1.0"
description = "utility scripts for processing CODEX spatial proteomics data"
readme = "README.md"
requires-python = ">=3.9,<3.11"
dependencies = [
    "cellpose",
    "magicgui",
    "matplotlib",
    "napari",
    "numpy>=1.26.4,<2",
    "opencv-python",
    "pandas",
    "pyarrow",
    "pyqt5",
    "pyyaml>=6.0.3",
    "scikit-bio",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "seaborn",
    "statsmodels",
    "tifffile",
    "umap-learn",
]

[project.optional-dependencies]
hpc = [
    "deepcell>=0.12.9",
    "gudhi>=3.10.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.15.9",
]
