#!/bin/bash

CONDITION="<TODO>"

DATA_DIRECTORY="<TODO>"
CELESTA_DIRECTORY="<TODO>"
SCRIPT_DIRECTORY="<TODO>"

SIGNATURE_MATRIX="$CELESTA_DIRECTORY/signature_matrices/$CONDITION/<TODO>.csv"

IMAGE_DIRECTORY="$DATA_DIRECTORY/$CONDITION"
ASSIGNMENTS_DIRECTORY="$IMAGE_DIRECTORY/assignments"
VISUALIZATION_DIRECTORY="$IMAGE_DIRECTORY/visualizations"
COLOCALIZATION_DIRECTORY="$IMAGE_DIRECTORY/colocalizations"

GLOBAL_COLOCALIZATION_SCRIPT="$SCRIPT_DIRECTORY/generate_condition_summaries.R"

Rscript "$GLOBAL_COLOCALIZATION_SCRIPT" \
    --data_directory "$ASSIGNMENTS_DIRECTORY" \
    --signature_matrix "$SIGNATURE_MATRIX" \
    --save_path "$COLOCALIZATION_DIRECTORY"