#!/bin/bash

CONDITION="<TODO>"

DATA_DIRECTORY="<TODO>"
CELESTA_DIRECTORY="<TODO>"
SCRIPT_DIRECTORY="<TODO>"

COLORMAP="<TODO>"

SIGNATURE_MATRIX="$CELESTA_DIRECTORY/signature_matrices/$CONDITION/<TODO>.csv"

IMAGE_DIRECTORY="$DATA_DIRECTORY/$CONDITION"
ASSIGNMENTS_DIRECTORY="$IMAGE_DIRECTORY/assignments"

LOCAL_COLOCALIZATION_SCRIPT="$SCRIPT_DIRECTORY/generate_spatial_embeddings.py"

python3 "$LOCAL_COLOCALIZATION_SCRIPT" \
    --colormap_path "$COLORMAP" \
    --data_directory "$ASSIGNMENTS_DIRECTORY" \
    --save_path "$IMAGE_DIRECTORY" \
    --signature_matrix "$SIGNATURE_MATRIX"